/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ProviderInventoryAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.InventoryOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class ManageProviderInventoryWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageInventoryWorkAreaJPanel
     */
    private JPanel container;
    private UserAccount account;
    private InventoryOrganization organization;
    private Enterprise enterprise;
    private EcoSystem business;

    public ManageProviderInventoryWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, InventoryOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.container = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.organization = organization;
        this.business = business;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        btnRequest = new javax.swing.JButton();
        btnReceiveRequest = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("Manage Inventory");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        btnView.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnView.setText("View Inventory");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 260, -1));

        btnRequest.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnRequest.setText("Request Inventory");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });
        add(btnRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 260, -1));

        btnReceiveRequest.setText("Received Request ");
        btnReceiveRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceiveRequestActionPerformed(evt);
            }
        });
        add(btnReceiveRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 260, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/background2.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        ViewProviderInventoryJPanel viewproviderinventory = new ViewProviderInventoryJPanel(container,account,organization,enterprise,business);
        container.add("ViewProviderInventoryJPanel", viewproviderinventory);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        // TODO add your handling code here:
        RequestProviderInventoryJPanel requestProviderInventoryJPanel = new RequestProviderInventoryJPanel(container,account,organization,enterprise,business);
        container.add("RequestProviderInventoryJPanel", requestProviderInventoryJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnRequestActionPerformed

    private void btnReceiveRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceiveRequestActionPerformed
        // TODO add your handling code here:
       RequestReceivedInventoryJPanel111111 requestProviderInventoryJPanel = new RequestReceivedInventoryJPanel111111(container,account,organization,enterprise,business);
        container.add("RequestProviderInventoryJPanel", requestProviderInventoryJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnReceiveRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReceiveRequest;
    private javax.swing.JButton btnRequest;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
