/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ProviderAdminWorkArea;

import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class ManageUserAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageUserAccountJPanel
     */
    private JPanel container;
    private Enterprise enterprise;
    private Organization organization;

    public ManageUserAccountJPanel(JPanel container, Enterprise enterprise, Organization organization) {
        initComponents();
        this.container = container;
        this.enterprise = enterprise;
        this.organization = organization;
        populateComboOrganization();;
        populateComboType();
    }
    
    private void populateComboOrganization(){
        comboOrganization.removeAllItems();
        for (Organization organization1 : enterprise.getOrganizationDirectory().getOrganizationList()){
                comboOrganization.addItem(organization1);
        }
    }
    
    private void populateComboType(){
        comboType.removeAllItems();
        for (Organization organization1 : enterprise.getOrganizationDirectory().getOrganizationList()){
                comboType.addItem(organization1);
        }
    }
    private void populateComboEmployee(Organization organization1){
        comboEmployee.removeAllItems();
        for(Employee employee :organization1.getEmployeeDirectory().getEmployeeList()){
            comboEmployee.addItem(employee);
        }
    }
    private void populateComboRole(Organization organization){
        comboRole.removeAllItems();
        for(Role role:organization.getSupportedRole()){
            comboRole.addItem(role);
        }
    }
    
    public void popData(Organization organization) {

        DefaultTableModel model = (DefaultTableModel) tblUserAccount.getModel();

        model.setRowCount(0);
        //Organization org =(Organization)comboOrganization.getSelectedItem();
            for (UserAccount ua : organization.getUserAccountDirectory().getUserAccountList()) {
                Object row[] = new Object[3];
                row[0]= ua.getEmployee().getName();
                row[1] = ua;
                row[2] = ua.getRole();
                ((DefaultTableModel) tblUserAccount.getModel()).addRow(row);
            }
        
    }
    
    public void populateTable() {

        DefaultTableModel model = (DefaultTableModel) tblUserAccount.getModel();

        model.setRowCount(0);
        for(Organization organization:enterprise.getOrganizationDirectory().getOrganizationList()){
            for (UserAccount ua : organization.getUserAccountDirectory().getUserAccountList()) {
                Object row[] = new Object[3];
                row[0]= ua.getEmployee().getName();
                row[1] = ua;
                row[2] = ua.getRole();
                ((DefaultTableModel) tblUserAccount.getModel()).addRow(row);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUserAccount = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        comboOrganization = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        comboType = new javax.swing.JComboBox();
        txtUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        comboEmployee = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        comboRole = new javax.swing.JComboBox();
        pswdPassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblUserAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Employee", "User Name", "Role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblUserAccount);
        if (tblUserAccount.getColumnModel().getColumnCount() > 0) {
            tblUserAccount.getColumnModel().getColumn(0).setResizable(false);
            tblUserAccount.getColumnModel().getColumn(1).setResizable(false);
            tblUserAccount.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 550, 140));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Organization:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        comboOrganization.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        comboOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboOrganizationActionPerformed(evt);
            }
        });
        add(comboOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 200, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Organization Type:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        comboType.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        comboType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTypeActionPerformed(evt);
            }
        });
        add(comboType, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 180, -1));

        txtUserName.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 180, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("User Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("Password:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, -1, -1));

        btnCreate.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnCreate.setText("Create User Account");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, -1, -1));

        btnBack.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("Employee:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        comboEmployee.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        add(comboEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 180, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("Role:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));

        comboRole.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        add(comboRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 180, -1));
        add(pswdPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 180, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel7.setText("Manage User Account");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        btnDelete.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, 80, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/background2.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void comboTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTypeActionPerformed
        // TODO add your handling code here:
        Organization organization1 = (Organization) comboType.getSelectedItem();
        if (organization1 != null){
            populateComboEmployee(organization1);
            populateComboRole(organization1);
        }
    }//GEN-LAST:event_comboTypeActionPerformed

    private void comboOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOrganizationActionPerformed
        // TODO add your handling code here:
         Organization organization1 = (Organization) comboOrganization.getSelectedItem();
        if (organization1 != null){
            popData(organization1);
        }
    }//GEN-LAST:event_comboOrganizationActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        Organization organization1 = (Organization) comboType.getSelectedItem();
        Employee employee = (Employee) comboEmployee.getSelectedItem();
        Role role = (Role) comboRole.getSelectedItem();
        String userName = txtUserName.getText();
        String password = String.valueOf(pswdPassword.getPassword());
        if((userName != null)&&!(userName.isEmpty()) && (password != null)&&!(password.isEmpty()) && (organization1 != null) && (employee != null) && (role != null))
        {
            Pattern pattern = Pattern.compile("[^A-Za-z0-9]");
            Matcher m = pattern.matcher(userName+password);
            boolean boo = m.find();
            if(boo == true || userName == null || password == null) {
                JOptionPane.showMessageDialog(null,"Enter Valid Details");
            }
            else{  
                UserAccount userAccount = organization1.getUserAccountDirectory().createUserAccount(userName, password, employee, role);
                System.out.println("00000"+organization1);
                populateTable();
            }
        }
        else {
            JOptionPane.showMessageDialog(null,"Enter Valid Details");
        }      
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblUserAccount.getSelectedRow();
        if(selectedRow>=0){
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to delete this record?", "Warning", dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION){
                UserAccount userAccount = (UserAccount)tblUserAccount.getValueAt(selectedRow, 1);
                System.out.println("ORG"+organization);
                Organization org31 = (Organization)comboOrganization.getSelectedItem();
                org31.getUserAccountDirectory().deleteUserAccount(userAccount);
                //  populateTable(org31);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select a row from the table first.","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JComboBox comboEmployee;
    private javax.swing.JComboBox comboOrganization;
    private javax.swing.JComboBox comboRole;
    private javax.swing.JComboBox comboType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField pswdPassword;
    private javax.swing.JTable tblUserAccount;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
