/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EnvironmentAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class EnvironmentAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageProviderWorkAreaJPanel
     */
    private JPanel container;
    private UserAccount account;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem business;

    public EnvironmentAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.container = userProcessContainer;
        this.account =account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        lblEnterprise.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblEnterprise = new javax.swing.JLabel();
        btnUserAccount = new javax.swing.JButton();
        btnOrganization = new javax.swing.JButton();
        btnEmployee = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("Environment Admin");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Enterprise:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        lblEnterprise.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblEnterprise.setText("name");
        add(lblEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 90, 20));

        btnUserAccount.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnUserAccount.setText("Manage User Account");
        btnUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserAccountActionPerformed(evt);
            }
        });
        add(btnUserAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 210, -1));

        btnOrganization.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnOrganization.setText("Manage Organization");
        btnOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrganizationActionPerformed(evt);
            }
        });
        add(btnOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 210, -1));

        btnEmployee.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnEmployee.setText("Manage Employee");
        btnEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeActionPerformed(evt);
            }
        });
        add(btnEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 210, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/background2.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserAccountActionPerformed
        // TODO add your handling code here:
        EnvironmentManageUserAccountJPanel environmentManageUserAccountJPanel = new EnvironmentManageUserAccountJPanel(container,account,organization,enterprise,business);
        container.add("EnvironmentManageOrganizationJPanel", environmentManageUserAccountJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnUserAccountActionPerformed

    private void btnEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeActionPerformed
        // TODO add your handling code here:
        EnvironmentManageEmployeeJPanel environmentManageEmployeeJPanel = new EnvironmentManageEmployeeJPanel(container,account,organization,enterprise,business);
        container.add("EnvironmentManageEmployeeJPanel", environmentManageEmployeeJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnEmployeeActionPerformed

    private void btnOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrganizationActionPerformed
        // TODO add your handling code here:
        EnvironmentManageOrganizationJPanel environmentManageOrganizationJPanel = new EnvironmentManageOrganizationJPanel(container,account,organization,enterprise,business);
        container.add("EnvironmentManageOrganizationJPanel", environmentManageOrganizationJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnOrganizationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmployee;
    private javax.swing.JButton btnOrganization;
    private javax.swing.JButton btnUserAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblEnterprise;
    // End of variables declaration//GEN-END:variables
}
