/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RentalAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.CityNetwork;
import Business.Network.CountryNetwork;
import Business.Network.StateNetwork;
import Business.Organization.InventoryOrganization;
import Business.Organization.Organization;
import Business.Organization.RentalOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.RentalWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class ManageRentalInventoryRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageInventoryRequestJPanel
     */
    private JPanel container;
    private UserAccount userAccount;
    private RentalOrganization organization;
    private Enterprise enterprise;
    private EcoSystem business;
  
    public ManageRentalInventoryRequestJPanel(JPanel container, UserAccount userAccount, RentalOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.container = container;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        populateTable();
    }
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)tblManageInventoryRequest.getModel();
        dtm.setRowCount(0);
        for(WorkRequest request: organization.getWorkQueue().getWorkRequestList()){
          //  if(request.getRentalorrender().equals("Render")){
                Object[] row1 = new Object[5];
                row1[0]=request.getSupplier();
                row1[1]=request.getProduct();
                row1[2]=request.getQuantity();
                row1[3]=request;
                row1[4]=request.getRentalorrender();
                dtm.addRow(row1);
         //   }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblManageInventoryRequest = new javax.swing.JTable();
        btnRentalRequest = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblManageInventoryRequest.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tblManageInventoryRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Supplier", "Product", "Status", "Quantity", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblManageInventoryRequest);
        if (tblManageInventoryRequest.getColumnModel().getColumnCount() > 0) {
            tblManageInventoryRequest.getColumnModel().getColumn(0).setResizable(false);
            tblManageInventoryRequest.getColumnModel().getColumn(1).setResizable(false);
            tblManageInventoryRequest.getColumnModel().getColumn(2).setResizable(false);
            tblManageInventoryRequest.getColumnModel().getColumn(3).setResizable(false);
            tblManageInventoryRequest.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 980, 420));

        btnRentalRequest.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnRentalRequest.setText("Rental Time");
        btnRentalRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentalRequestActionPerformed(evt);
            }
        });
        add(btnRentalRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 520, 190, 40));

        btnBack.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/background2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRentalRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentalRequestActionPerformed
        // TODO add your handling code here:     
       int selectedRow = tblManageInventoryRequest.getSelectedRow();
       
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
        Enterprise supplier = (Enterprise)tblManageInventoryRequest.getValueAt(selectedRow,0);
       RentalWorkRequest rental1 = (RentalWorkRequest)tblManageInventoryRequest.getValueAt(selectedRow, 3);
       rental1.setStatus("Processing");
     //  String name =String.valueOf(tblManageInventoryRequest.getValueAt(selectedRow,3));
      // Object supp = name;
     // CHecking Start
     
     
     /*
       Organization org = null;
           for(Organization organization1:supp1.getOrganizationDirectory().getOrganizationList()){
               System.out.println("organization"+organization1);
               System.out.println("1234422"+(organization1 instanceof InventoryOrganization));
               if(organization1 instanceof InventoryOrganization){
                   org =organization1;
                   break;
               }
           }
           
            if(org != null){
              org.getWorkQueue().getWorkRequestList().add(rental1);
              
              organization.getWorkQueue().getWorkRequestList().add(rental1);
              System.out.println("honey"+organization.getWorkQueue().getWorkRequestList());
               userAccount.getWorkqueue().getWorkRequestList().add(rental1);
         }
       */     
            
    //CHEcking end        
     //   System.out.println("sweety"+tblManageInventoryRequest.getValueAt(selectedRow,3));
      //  LabTestWorkRequest request = (RentalWorkRequest)tblManageInventoryRequest.getValueAt(selectedRow, 0);
     
       // request.setStatus("Processing");
        
        RentalDateJPanel rentaldate = new RentalDateJPanel(container,userAccount,organization,enterprise,business,rental1,supplier);
        container.add("RentalDateJPanel", rentaldate);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
        // Enterprise supplier = (Enterprise)comboSupplier.getSelectedItem();
    }//GEN-LAST:event_btnRentalRequestActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRentalRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblManageInventoryRequest;
    // End of variables declaration//GEN-END:variables
}
