/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RentalAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.RentalOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class RentalAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RentalAdminWorkAreaJPanel
     */
    private JPanel container;
    private UserAccount userAccount;
    private RentalOrganization organization;
    private Enterprise enterprise;
    private EcoSystem business;

    public RentalAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, RentalOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.container = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageInventoryRequest = new javax.swing.JButton();
        btnRequestSupplier = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnManageInventoryRequest.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnManageInventoryRequest.setText("Manage Inventory Request");
        btnManageInventoryRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageInventoryRequestActionPerformed(evt);
            }
        });
        add(btnManageInventoryRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        btnRequestSupplier.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnRequestSupplier.setText("Request Supplier");
        btnRequestSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestSupplierActionPerformed(evt);
            }
        });
        add(btnRequestSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 200, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("Rental");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/background2.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageInventoryRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageInventoryRequestActionPerformed
        // TODO add your handling code here:
        ManageRentalInventoryRequestJPanel mrirjp = new ManageRentalInventoryRequestJPanel(container,userAccount,organization,enterprise,business);
        container.add("ManageRentalInventoryRequestJPanel", mrirjp);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnManageInventoryRequestActionPerformed

    private void btnRequestSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestSupplierActionPerformed
        // TODO add your handling code here:
        RequestRentalSupplierJPanel requestrentalsupplier = new RequestRentalSupplierJPanel(container,userAccount,organization,enterprise,business);
        container.add("RequestRentalSupplierJPanel", requestrentalsupplier);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnRequestSupplierActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageInventoryRequest;
    private javax.swing.JButton btnRequestSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
