/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RentalAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.InventoryOrganization;
import Business.Organization.Organization;
import Business.Organization.RentalOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.RentalWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class RentalDateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RentalDateJPanel
     */
    private JPanel container;
    private UserAccount userAccount;
    private RentalOrganization organization;
    private Enterprise enterprise;
    private EcoSystem business;
    private RentalWorkRequest rental1;
    private Enterprise supp1;
  
    public RentalDateJPanel(JPanel container, UserAccount userAccount, RentalOrganization organization, Enterprise enterprise, EcoSystem business, RentalWorkRequest rental1, Enterprise supp1) {
        initComponents();
        this.container = container;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        this.rental1 = rental1;
        this.supp1 = supp1;
        txtProduct.setText(rental1.getProduct());
        txtSupplier.setText(String.valueOf(rental1.getSupplier()));
        txtQuantities.setText(String.valueOf(rental1.getQuantity()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtProduct = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSupplier = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtQuantities = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnAddRentingRequest = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        dateChooserComboFrom = new datechooser.beans.DateChooserCombo();
        dateChooserComboTo = new datechooser.beans.DateChooserCombo();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("Rental Time");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Product:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        txtProduct.setEditable(false);
        txtProduct.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtProduct.setEnabled(false);
        add(txtProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 160, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("Supplier:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));

        txtSupplier.setEditable(false);
        txtSupplier.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtSupplier.setEnabled(false);
        add(txtSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 160, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("Quantities:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        txtQuantities.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtQuantities.setEnabled(false);
        add(txtQuantities, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 160, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("From:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("To:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, -1));

        btnAddRentingRequest.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnAddRentingRequest.setText("Add Renting Request");
        btnAddRentingRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRentingRequestActionPerformed(evt);
            }
        });
        add(btnAddRentingRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, -1, -1));

        btnBack.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, -1, -1));

        dateChooserComboFrom.setCurrentView(new datechooser.view.appearance.AppearancesList("Grey",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dateChooserComboFrom.setCalendarBackground(new java.awt.Color(204, 204, 204));
    dateChooserComboFrom.setNothingAllowed(false);
    dateChooserComboFrom.setFieldFont(new java.awt.Font("Verdana", java.awt.Font.PLAIN, 12));
    dateChooserComboFrom.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_SINGLE);
    add(dateChooserComboFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 160, -1));

    dateChooserComboTo.setCurrentView(new datechooser.view.appearance.AppearancesList("Grey",
        new datechooser.view.appearance.ViewAppearance("custom",
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                true,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                new java.awt.Color(0, 0, 255),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                new java.awt.Color(128, 128, 128),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(255, 0, 0),
                false,
                false,
                new datechooser.view.appearance.swing.ButtonPainter()),
            (datechooser.view.BackRenderer)null,
            false,
            true)));
dateChooserComboTo.setCalendarBackground(new java.awt.Color(204, 204, 204));
dateChooserComboTo.setNothingAllowed(false);
dateChooserComboTo.setFieldFont(new java.awt.Font("Verdana", java.awt.Font.PLAIN, 12));
dateChooserComboTo.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_SINGLE);
add(dateChooserComboTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 160, -1));

jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/background2.png"))); // NOI18N
jLabel7.setText("jLabel7");
add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));
}// </editor-fold>//GEN-END:initComponents

    private void btnAddRentingRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRentingRequestActionPerformed
        // TODO add your handling code here:
        
        
        
        String join1 = dateChooserComboFrom.getText();
        Date joindate = new Date();
        try {
             joindate =new SimpleDateFormat("MM/dd/yyyy").parse(join1);
             rental1.setFrom(joindate);
              
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Please enter a valid date");
        }
        
        String join2 = dateChooserComboTo.getText();
        Date joindate1 = new Date();
        try {
             joindate1 =new SimpleDateFormat("MM/dd/yyyy").parse(join2);
             rental1.setTo(joindate1);
              
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Please enter a valid date");
        }
        
        
        
        Organization org = null;
           for(Organization organization1:supp1.getOrganizationDirectory().getOrganizationList()){
               System.out.println("organization"+organization1);
               System.out.println("1234422"+(organization1 instanceof InventoryOrganization));
               if(organization1 instanceof InventoryOrganization){
                   org =organization1;
                   break;
               }
           }
           
            if(org != null){
              rental1.setReceiver(null);
              org.getWorkQueue().getWorkRequestList().add(rental1);
              
              organization.getWorkQueue().getWorkRequestList().add(rental1);
              System.out.println("honey"+organization.getWorkQueue().getWorkRequestList());
               userAccount.getWorkqueue().getWorkRequestList().add(rental1);
               for(WorkRequest rental:org.getWorkQueue().getWorkRequestList()){
                   System.out.println("*@#"+rental.getQuantity()+"*@#"+rental.getTo());
               }
         }
        
       // System.out.println("HEEEEEEEEYYYY"+rental1.getFrom());
    }//GEN-LAST:event_btnAddRentingRequestActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRentingRequest;
    private javax.swing.JButton btnBack;
    private datechooser.beans.DateChooserCombo dateChooserComboFrom;
    private datechooser.beans.DateChooserCombo dateChooserComboTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtProduct;
    private javax.swing.JTextField txtQuantities;
    private javax.swing.JTextField txtSupplier;
    // End of variables declaration//GEN-END:variables
}
