/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RentalAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.RentalOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.RentalWorkRequest;
import Business.WorkQueue.WorkRequest;
import userinterface.RenderAdminWorkArea.*;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class RequestRentalSupplierJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestSupplierJPanel
     */
    private JPanel container;
    private  UserAccount userAccount;
    private RentalOrganization organization;
    private Enterprise enterprise;
    private EcoSystem business;

    public RequestRentalSupplierJPanel(JPanel container, UserAccount userAccount, RentalOrganization organization, Enterprise enterprise, EcoSystem business) {
         initComponents();
        this.container = container;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.business = business;
        this.organization = organization;
        populateTable();

    }

     public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)tblSupplierRequest.getModel();
        dtm.setRowCount(0);
        for(WorkRequest request :userAccount.getWorkqueue().getWorkRequestList()){
          //  if(request.getRentalorrender().equals("Render")){
                Object[] row1 = new Object[8];
                row1[0]=request.getSupplier();
                row1[1]=request.getProduct();
                row1[2]=request.getStatus();
                row1[3]=request.getQuantity();
                row1[4]=request.getSender().getEmployee().getName();
                row1[5]=request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
                row1[6]=request.getFrom();
                row1[7]=request.getTo();
                dtm.addRow(row1);
               
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSupplierRequest = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, -1, -1));

        tblSupplierRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Supplier", "Product", "Status", "Quantity", "Sender", "Receiver", "From", "To"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSupplierRequest);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 950, 500));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("Request Rental Supplier");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/background2.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSupplierRequest;
    // End of variables declaration//GEN-END:variables
}
