/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RenderAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.CityNetwork;
import Business.Network.CountryNetwork;
import Business.Network.StateNetwork;
import Business.Organization.InventoryOrganization;
import Business.Organization.Organization;
import Business.Organization.RenderOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.RenderWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class ManageInventoryRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageInventoryRequestJPanel
     */
    private JPanel container;
    private UserAccount account;
    private RenderOrganization renderOrganization;
    private Enterprise enterprise;
    private EcoSystem business;
    
    public ManageInventoryRequestJPanel(JPanel container, UserAccount account, RenderOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.container = container;
        this.account = account;
        this.renderOrganization = organization;
        this.enterprise = enterprise;
        this.business = business;
        populateTable();
    }

     private void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)tblManageInventoryRequest.getModel();
        dtm.setRowCount(0);
         System.out.println("ORGANIZATIONNAME"+renderOrganization);
         System.out.println("OKK"+renderOrganization.getWorkQueue().getWorkRequestList());
        for(WorkRequest request: renderOrganization.getWorkQueue().getWorkRequestList()){
            
            Object[] row1 = new Object[5];
            
            row1[0]=request.getSupplier();
            row1[1]=request.getProduct();
            row1[2]=request;
            row1[3]=request.getQuantity();
            row1[4]=request.getRentalorrender();
            dtm.addRow(row1);
        }
    }
    
    /*
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)tblManageInventoryRequest.getModel();
        dtm.setRowCount(0);
        for(WorkRequest request: organization.getWorkQueue().getWorkRequestList()){
          //  if(request.getRentalorrender().equals("Render")){
                Object[] row1 = new Object[7];
                row1[0]=request;
                row1[1]=request.getSender().getEmployee().getName();
                row1[2]=request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();;
                row1[3]=request.getSupplier();
                row1[4]=request.getProduct();
                row1[5]=request.getStatus();
                row1[6]=request.getQuantity();
                dtm.addRow(row1);
         //   }
        }
    }
    */
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblManageInventoryRequest = new javax.swing.JTable();
        btnForwardRequest = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblManageInventoryRequest.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tblManageInventoryRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Supplier", "Product", "Status", "Quantity", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblManageInventoryRequest);
        if (tblManageInventoryRequest.getColumnModel().getColumnCount() > 0) {
            tblManageInventoryRequest.getColumnModel().getColumn(0).setResizable(false);
            tblManageInventoryRequest.getColumnModel().getColumn(1).setResizable(false);
            tblManageInventoryRequest.getColumnModel().getColumn(2).setResizable(false);
            tblManageInventoryRequest.getColumnModel().getColumn(3).setResizable(false);
            tblManageInventoryRequest.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 960, 380));

        btnForwardRequest.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnForwardRequest.setText("Forward Request to Supplier");
        btnForwardRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForwardRequestActionPerformed(evt);
            }
        });
        add(btnForwardRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, -1, -1));

        btnBack.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/background2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void btnForwardRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForwardRequestActionPerformed
        // TODO add your handling code here:
       // RequestSupplierJPanel requestsupplier = new RequestSupplierJPanel(container);
       // container.add("RequestSupplierJPanel", requestsupplier);
       
      // Enterprise supplier = (Enterprise)comboSupplier.getSelectedItem();
       
        int selectedRow = tblManageInventoryRequest.getSelectedRow();
        
        
        //System.out.println("SPP"+supplier1);
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
        Enterprise supplier1 = (Enterprise)tblManageInventoryRequest.getValueAt(selectedRow,0);
        RenderWorkRequest render = (RenderWorkRequest)tblManageInventoryRequest.getValueAt(selectedRow, 2);
         render.setStatus("Requested");
        Organization org = null;
           for(Organization organization1:supplier1.getOrganizationDirectory().getOrganizationList()){
               System.out.println("organization"+organization1);
               System.out.println("1234422"+(organization1 instanceof InventoryOrganization));
               if(organization1 instanceof InventoryOrganization){
                   org =organization1;
                   break;
               }
           }
           
          if(org != null){
              render.setReceiver(null);
              render.setSender(account);
             org.getWorkQueue().getWorkRequestList().add(render);
              System.out.println("honey"+org.getWorkQueue().getWorkRequestList());
               account.getWorkqueue().getWorkRequestList().add(render);
               System.out.println("RDACCOUNT"+account.getWorkqueue().getWorkRequestList());
               System.out.println("SUPPINVORG"+org.getWorkQueue().getWorkRequestList());
         }
       
    }//GEN-LAST:event_btnForwardRequestActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnForwardRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblManageInventoryRequest;
    // End of variables declaration//GEN-END:variables
}
