/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EnvironmentDataCollectingAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.EnvironmentalDataCollectingOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author rishabhjain
 */
public class EnvironmentalDataCollectorMainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EnvironmentalDataCollectorMainJPanel
     */
    private JPanel container;
    private UserAccount account;
    private EnvironmentalDataCollectingOrganization  organization;
    private Enterprise enterprise;
    private EcoSystem business;

    public EnvironmentalDataCollectorMainJPanel(JPanel userProcessContainer, UserAccount account, EnvironmentalDataCollectingOrganization  organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.container = userProcessContainer;
        this.account = account;
        this.organization =organization;
        this.enterprise = enterprise;
        this.business=business;
        System.out.println("QQ"+organization);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnviewcollecteddata = new javax.swing.JButton();
        btncollectdata = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("DATA COLLECTING INFORMATION");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        btnviewcollecteddata.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnviewcollecteddata.setText("VIEW COLLECTED DATA");
        btnviewcollecteddata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewcollecteddataActionPerformed(evt);
            }
        });
        add(btnviewcollecteddata, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 250, -1));

        btncollectdata.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btncollectdata.setText("COLLECT DATA");
        btncollectdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncollectdataActionPerformed(evt);
            }
        });
        add(btncollectdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 250, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/background2.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void btncollectdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncollectdataActionPerformed
        // TODO add your handling code here:
         EnvironmentDataCollectingAdminWorkAreaJPanel environmentassign = new EnvironmentDataCollectingAdminWorkAreaJPanel(container,account,organization,enterprise,business);
        container.add("EnvironmentDataCollectingJPanel", environmentassign);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btncollectdataActionPerformed

    private void btnviewcollecteddataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewcollecteddataActionPerformed
        // TODO add your handling code here:
        ViewCollectedDataJPanel environmentassign1 = new ViewCollectedDataJPanel(container,account,organization,enterprise,business);
        container.add("ViewCollectedDataJPanel", environmentassign1);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnviewcollecteddataActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncollectdata;
    private javax.swing.JButton btnviewcollecteddata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
