/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EnvironmentDataCollectingAdminWorkArea;

import Business.Assignment.Assignment;
import Business.Data.Data;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.EnvironmentalAssignOrganization;
import Business.Organization.EnvironmentalDataCollectingOrganization;
import Business.Organization.InventoryOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rishabhjain
 */
public class ViewCollectedDataJPanel extends javax.swing.JPanel {

    
    /**
     * Creates new form ViewCollectedDataJPanel
     */
    private JPanel container;
    private UserAccount account;
    private EnvironmentalDataCollectingOrganization  organization;
    private Enterprise enterprise;
    private EcoSystem business;

    public ViewCollectedDataJPanel(JPanel container, UserAccount account, EnvironmentalDataCollectingOrganization  organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.container = container;
        this.account = account;
        this.organization =organization;
        this.enterprise = enterprise;
        this.business=business;
        //populateTable();
      populateComboBox();
    }
    
    public void populateComboBox(){
       
        comboCity.removeAllItems();
      //  for(Organization organization2:enterprise.getOrganizationDirectory().getOrganizationList()){
            System.out.println("11"+organization);
        //    if(organization2 instanceof EnvironmentalDataCollectingOrganization){
                System.out.println("12"+organization.getAssignmentdirectory().getAssignmentList());
        
    for(Assignment assignment: organization.getAssignmentdirectory().getAssignmentList()){
        String assign = new String();
        if(!assign.equalsIgnoreCase(String.valueOf(assignment))){
        System.out.println("AAA"+assignment.getCity());
        comboCity.addItem(assignment.getCity());
        }
    }
   // }
    //    }
    }
    
    public void populateTable(Object city){
      
      DefaultTableModel dtm = (DefaultTableModel)tblAssign.getModel();
       dtm.setRowCount(0);
          
           Object[] row1 = new Object[10];
   // String c = String.valueOf(comboCity.getSelectedItem());
     
   // for(Organization organization2:enterprise.getOrganizationDirectory().getOrganizationList()){
            //System.out.println("AAAAA"+String.valueOf(organization2).equals("Environmental Assign Organization"));
            System.out.println("11"+organization);
          //  System.out.println("12"+organization2.getAssignmentdirectory().getAssignmentList());
         //   if(organization2 instanceof EnvironmentalDataCollectingOrganization){
                System.out.println("12"+organization.getAssignmentdirectory().getAssignmentList());
    for(Assignment assignment: organization.getAssignmentdirectory().getAssignmentList()){
        System.out.println("CITYCHECKING"+String.valueOf(city).equals(String.valueOf(assignment.getCity())));
      if(String.valueOf(city).equals(String.valueOf(assignment.getCity()))){
        for(Data data:assignment.getDatadirectory().getDataList()){
        row1[0]=assignment.getProductName();
        row1[1]=assignment.getCountry();
        row1[2]=assignment.getState();
        row1[3]=assignment.getCity();
        row1[4]=assignment.getLocation();
        row1[5]=assignment.getZipcode();
        row1[6]=data.getDate();
        row1[7]=data.getWindspeed();
        row1[8]=data.getTemperature();
        row1[9]= data.getHumidity();    
        
        dtm.addRow(row1);
    //   }
      }}
       }
    }

   // }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboCity = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAssign = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("VIEW COLLECTED INFORMATION");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        comboCity.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        comboCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCityActionPerformed(evt);
            }
        });
        add(comboCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 210, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("City");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 40, 20));

        tblAssign.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tblAssign.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Product Name", "Country", "State", "City", "Location", "ZipCode", "Date", "Windspeed(m/s)", "Temperature(°C)", "Humidity(%)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblAssign);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 1040, 450));

        btnBack.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/background2.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void comboCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCityActionPerformed
        // TODO add your handling code here:
         Object city = comboCity.getSelectedItem();
        if (city != null){
            populateTable(city);
        }
    }//GEN-LAST:event_comboCityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox comboCity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblAssign;
    // End of variables declaration//GEN-END:variables
}
