/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.graph;

import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.text.MessageFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.text.Document;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.BarRenderer3D;
import org.jfree.data.category.DefaultCategoryDataset;
import userinterface.ProviderInventoryAdminWorkArea.ViewProviderInventoryJPanel;
import userinterface.email.MailApp;
import userinterface.sms.SMSJFrame;


/**
 *
 * @author rishabhjain
 */
public class ShowGraphJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ShowGraph
     */
    private JPanel container;
    private float avgtemp;
    private float avghum;
    private float avgwind;
    private Date From;
    private Date To;


    public ShowGraphJPanel(JPanel container, float avghumidity1, float avgtemperature1, float avgwindspeed1, Date From, Date To) {
        initComponents();
        this.container = container;
        this.avghum = avghumidity1;
        this.avgtemp = avgtemperature1;
        this.avgwind = avgwindspeed1;
        this.From = From;
        this.To = To;
        lblFrom.setText(String.valueOf(this.To));
        lblTo.setText(String.valueOf(this.From));
        
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(avgwind, "", "Wind Speed");
        dataset.setValue(avgtemp, "", "Temperature");
        dataset.setValue(avghum, "", "Humidity");

        JFreeChart chart = ChartFactory.createBarChart("Weather Information","","", dataset, PlotOrientation.VERTICAL, false,false,false);
        chart.setBackgroundPaint(Color.YELLOW);
        chart.getTitle().setPaint(Color.BLUE);
        chart.setBorderPaint(Color.BLACK);
        
        
        
        
        
        
        
        
        
        
        CategoryPlot catPlot = chart.getCategoryPlot();
        BarRenderer customBarRenderer = (BarRenderer) catPlot.getRenderer();
        catPlot.setRangeGridlinePaint(Color.BLACK);
        System.out.println("CHECKCONDITION"+(((avgwind < 3.0) && (avgtemp < 25) && (avghum > 20)) || ((avgwind > 3.0) && (avgtemp > 25) && (avghum > 20)) || ((avgwind > 3.0) && (avgtemp < 25) && (avghum < 20))));
        
        
       if((avgwind < 3.0) && (avgtemp > 25) && (avghum < 20)){
           System.out.println("1");
        customBarRenderer.setSeriesPaint(0, Color.decode("#FF0000"));
       }
       else if (((avgwind < 3.0) && (avgtemp > 25) && (avghum > 20)) || ((avgwind < 3.0) && (avgtemp < 25) && (avghum < 20)) || ((avgwind > 3.0) && (avgtemp > 25) && (avghum < 20))){
           System.out.println("2");
           customBarRenderer.setSeriesPaint(0, Color.decode("#FFA500"));
       }
       else if(((avgwind < 3.0) && (avgtemp < 25) && (avghum > 20)) || ((avgwind > 3.0) && (avgtemp > 25) && (avghum > 20)) || ((avgwind > 3.0) && (avgtemp < 25) && (avghum < 20))){
           System.out.println("3");
           customBarRenderer.setSeriesPaint(0, Color.decode("#FFFFF00")); 
       }
       else
       {
           System.out.println("4");
           customBarRenderer.setSeriesPaint(0, Color.decode("#008000"));
       }
       
       
       
       
        ChartPanel chartPanel = new ChartPanel(chart);
        chartJPanel.removeAll();
        chartJPanel.add(chartPanel,BorderLayout.CENTER);
        chartJPanel.validate();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chartJPanel = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        lblFrom = new javax.swing.JLabel();
        lblTo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnSendEmail = new javax.swing.JButton();
        btnSendSMS = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chartJPanel.setBackground(java.awt.Color.gray);
        chartJPanel.setLayout(new java.awt.BorderLayout());
        add(chartJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 730, 510));

        btnBack.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, -1, -1));

        lblFrom.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(lblFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 580, 200, 20));

        lblTo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(lblTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 580, 260, 20));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("Date From:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("DateTo:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 580, -1, -1));

        label2.setBackground(new java.awt.Color(255, 0, 0));
        add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 230, 40, 30));

        label3.setBackground(new java.awt.Color(0, 128, 0));
        add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 110, 40, 30));

        label4.setBackground(new java.awt.Color(255, 255, 0));
        add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 150, 40, 30));

        label5.setBackground(new java.awt.Color(255, 165, 0));
        add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 190, 40, 30));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("CHANCE OF FOREST FIRE");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 50, 170, 50));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("SAFE");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 110, 80, 30));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setText("MODERATE");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 150, 80, 30));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setText("HIGH");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 190, 80, 30));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel7.setText("VERY HIGH");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 230, 80, 30));

        btnSendEmail.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnSendEmail.setText("SEND EMAIL");
        btnSendEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendEmailActionPerformed(evt);
            }
        });
        add(btnSendEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 340, 220, 40));

        btnSendSMS.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnSendSMS.setText("SEND MESSAGE");
        btnSendSMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendSMSActionPerformed(evt);
            }
        });
        add(btnSendSMS, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 390, 220, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/background2.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSendEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendEmailActionPerformed
        // TODO add your handling code here:
        
      new MailApp().setVisible(true);
     // new MailApp().setSize(500, 600);
    }//GEN-LAST:event_btnSendEmailActionPerformed

    private void btnSendSMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendSMSActionPerformed
        // TODO add your handling code here:
        new SMSJFrame().setVisible(true);
    }//GEN-LAST:event_btnSendSMSActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSendEmail;
    private javax.swing.JButton btnSendSMS;
    private javax.swing.JPanel chartJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblTo;
    // End of variables declaration//GEN-END:variables
}
