/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EnvironmentAssignAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.EnvironmentalAssignOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class EnvironmentAssignAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EnvironmentAssignAdminWorkAreaJPanel
     */
    private JPanel container;
    private UserAccount account;
    private Enterprise enterprise;
    private EnvironmentalAssignOrganization organization;
    private EcoSystem business;
   
    public EnvironmentAssignAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, EnvironmentalAssignOrganization  organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.container = userProcessContainer;
        this.account = account;
        this.organization =organization;
        this.enterprise = enterprise;
        this.business=business;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAssign = new javax.swing.JButton();
        btnViewAssignment = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("Assign Admin Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        btnAssign.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnAssign.setText("Assign UAV");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        add(btnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 140, -1));

        btnViewAssignment.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnViewAssignment.setText("View Assignment");
        btnViewAssignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAssignmentActionPerformed(evt);
            }
        });
        add(btnViewAssignment, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/background2.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        EnvironmentAssignJPanel environmentassign = new EnvironmentAssignJPanel(container,account,organization,enterprise,business);
        container.add("EnvironmentAssignJPanel", environmentassign);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnViewAssignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAssignmentActionPerformed
        // TODO add your handling code here:
        EnvironmentViewStatusJPanel environmentviewstatus = new EnvironmentViewStatusJPanel(container,account,organization,enterprise,business);
        container.add("EnvironmentViewStatusJPanel", environmentviewstatus);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnViewAssignmentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnViewAssignment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
