/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EnvironmentAssignAdminWorkArea;

import Business.Assignment.Assignment;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.EnvironmentalAssignOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class EnvironmentViewStatusJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EnvironmentViewStatusJPanel
     */
    private JPanel container;
    private UserAccount account;
    private Enterprise enterprise;
    private EnvironmentalAssignOrganization  organization;
    private EcoSystem business;

    public EnvironmentViewStatusJPanel(JPanel container, UserAccount account, EnvironmentalAssignOrganization  organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.container = container;
        this.account = account;
        this.organization =organization;
        this.enterprise = enterprise;
        this.business=business;
        System.out.println("SSSS"+organization);
        System.out.println(organization.getAssignmentdirectory().getAssignmentList());
        populateTable();
    }

    public void populateTable(){
      
      DefaultTableModel dtm = (DefaultTableModel)tblAssign.getModel();
       dtm.setRowCount(0);
          
           Object[] row1 = new Object[7];
 
     
    
    for(Assignment assignment: organization.getAssignmentdirectory().getAssignmentList()){
        
        row1[0]=assignment.getAssignmentId();
        row1[1]=assignment.getProductName();
        row1[2]=assignment.getCountry();
        row1[3]=assignment.getState();
        row1[4]=assignment.getCity();
        row1[5]=assignment.getLocation();
        row1[6]=assignment.getZipcode();
        dtm.addRow(row1);
    }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblAssign = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblAssign.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tblAssign.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Product Name", "Country", "State", "City", "Location", "ZipCode"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblAssign);
        if (tblAssign.getColumnModel().getColumnCount() > 0) {
            tblAssign.getColumnModel().getColumn(0).setResizable(false);
            tblAssign.getColumnModel().getColumn(1).setResizable(false);
            tblAssign.getColumnModel().getColumn(2).setResizable(false);
            tblAssign.getColumnModel().getColumn(3).setResizable(false);
            tblAssign.getColumnModel().getColumn(4).setResizable(false);
            tblAssign.getColumnModel().getColumn(5).setResizable(false);
            tblAssign.getColumnModel().getColumn(6).setResizable(false);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 960, 430));

        jButton1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 630, -1, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("View Assign Status");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/background2.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblAssign;
    // End of variables declaration//GEN-END:variables
}
