 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PayrollAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class PayrollAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PayrollAdminWorkAreaJPanel
     */
    private JPanel container;
    private UserAccount account;
    private Enterprise enterprise;
    private Organization organization;
    private EcoSystem business;
    
    public PayrollAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.container = userProcessContainer;
        this.enterprise = enterprise;
        this.organization = organization;
        this.business = business;
        this.account = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManagePayment = new javax.swing.JButton();
        btnViewPayment = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("Payroll");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        btnManagePayment.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnManagePayment.setText("Manage Payments");
        btnManagePayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePaymentActionPerformed(evt);
            }
        });
        add(btnManagePayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 280, -1));

        btnViewPayment.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnViewPayment.setText("View Employee Payment");
        btnViewPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPaymentActionPerformed(evt);
            }
        });
        add(btnViewPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 280, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/background2.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPaymentActionPerformed
        // TODO add your handling code here:
        ViewEmployeePaymentJPanel viewpayment = new ViewEmployeePaymentJPanel(container,account,organization,enterprise,business);
        container.add("ViewEmployeePaymentJPanel", viewpayment);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnViewPaymentActionPerformed

    private void btnManagePaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePaymentActionPerformed
        // TODO add your handling code here:
        ManagePaymentJPanel payment = new ManagePaymentJPanel(container,account,organization,enterprise,business);
        container.add("ManagePaymentJPanel", payment);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnManagePaymentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManagePayment;
    private javax.swing.JButton btnViewPayment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
