/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PayrollAdminWorkArea;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.PayRoll.PayRoll;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class ViewEmployeePaymentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewEmployeePaymentJPanel
     */
    private JPanel container;
    private UserAccount account;
    private Enterprise enterprise;
    private Organization organization;
    private EcoSystem business;
   private static float rate=0;

    ViewEmployeePaymentJPanel(JPanel container, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.container = container;
        this.enterprise = enterprise;
        this.organization = organization;
        this.business = business;
        this.account = account;
        populateComboEmployee();
        populateTable();
    }
     private void populateComboEmployee(){
        comboEmployeeName.removeAllItems();
        for(Organization organization1:enterprise.getOrganizationDirectory().getOrganizationList()){
        for(Employee employee :organization1.getEmployeeDirectory().getEmployeeList()){
            comboEmployeeName.addItem(employee);
        }
        }
     }
    private void populateTable(){
   
        DefaultTableModel dtm;
        dtm = (DefaultTableModel)tblPayroll.getModel();
        dtm.setRowCount(0);
        for(PayRoll payroll:organization.getPayRollDirectory().getPayRoleList()){
            Object[] row = new Object[6];
            row[0]=payroll.getId();
            row[1]=payroll.getEmployee().getName();
            row[2]=payroll.getFrom();
            row[3]=payroll.getTo();
            row[4]=payroll.getHours();
            row[5]=payroll.getSalary();
            dtm.addRow(row);
        }
    }
        private void populateTable1(Employee employee){
   
        DefaultTableModel dtm;
        dtm = (DefaultTableModel)tblPayroll.getModel();
        dtm.setRowCount(0);
        for(PayRoll payroll:organization.getPayRollDirectory().getPayRoleList()){
            if(payroll.getEmployee().getName().equals(String.valueOf(employee))){
            Object[] row = new Object[6];
            row[0]=payroll.getId();
            row[1]=payroll.getEmployee().getName();
            row[2]=payroll.getFrom();
            row[3]=payroll.getTo();
            row[4]=payroll.getHours();
            row[5]=payroll;
            dtm.addRow(row);
            }
        }
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPayroll = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        comboEmployeeName = new javax.swing.JComboBox();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPayroll.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tblPayroll.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Payrollid", "Employee", "From", "To", "Total WorkHours", "Salary"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPayroll);
        if (tblPayroll.getColumnModel().getColumnCount() > 0) {
            tblPayroll.getColumnModel().getColumn(5).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 970, 470));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Employee:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        comboEmployeeName.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        comboEmployeeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEmployeeNameActionPerformed(evt);
            }
        });
        add(comboEmployeeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 180, -1));

        btnBack.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/background2.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void comboEmployeeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEmployeeNameActionPerformed
        // TODO add your handling code here:
        Employee emp = (Employee)comboEmployeeName.getSelectedItem();
        if(emp != null){
            populateTable1(emp);
        }
    }//GEN-LAST:event_comboEmployeeNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox comboEmployeeName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPayroll;
    // End of variables declaration//GEN-END:variables
}
