/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ForestProtectorRequestData;

import Business.DataWorkQueue.DataWorkRequest;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.ForestProtectorRequestDataOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.text.MessageFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import userinterface.graph.ShowGraphJPanel;

/**
 *
 * @author rishabhjain
 */
public class AnalyzeDataJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AnalyzeDataJPanel
     */
    private JPanel container;
    private UserAccount account;
    private ForestProtectorRequestDataOrganization organization;
    private Enterprise enterprise;
    private EcoSystem business;


    public AnalyzeDataJPanel(JPanel container, UserAccount account, ForestProtectorRequestDataOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.container = container;
        this.account =account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        populateTable();
    }
    private void populateTable(){
   
        DefaultTableModel dtm;
        dtm = (DefaultTableModel)tblAssign.getModel();
        dtm.setRowCount(0);
        for(DataWorkRequest data:account.getDataWorkQueue().getDataworkRequestList()){
            Object[] row1 = new Object[4];
            row1[0]=data.getDateofData();
            row1[1]=data.getWindspeed();
            row1[2]=data.getTemperature();
            row1[3]=data.getHumidity();
            dtm.addRow(row1)  ;
           
       
       }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAssign = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnGraph = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("ANALYZE DATA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));

        tblAssign.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tblAssign.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Windspeed(m/s)", "Temperature(°C)", "Humidity(%)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblAssign);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 940, 440));

        btnBack.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 620, -1, -1));

        btnGraph.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnGraph.setText("SHOW GRAPH");
        btnGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraphActionPerformed(evt);
            }
        });
        add(btnGraph, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 580, 220, 50));

        btnPrint.setText("PRINT");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintOnClickActionPerformed(evt);
            }
        });
        add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 579, 190, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/background2.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraphActionPerformed
        // TODO add your handling code here:
        float avgtemp =0,avgwindspeed=0,avghumidity=0;
        float avgtemperature1 =0,avghumidity1 =0,avgwindspeed1 =0;
        int count=0;
        Date To = new Date();
        Date From = new Date();
        for(DataWorkRequest data:account.getDataWorkQueue().getDataworkRequestList()){
           To = data.getFrom();
           From = data.getTo();
            avgtemp = avgtemp+data.getTemperature();
            avgwindspeed = avgwindspeed+data.getWindspeed();
            avghumidity = avghumidity + data.getHumidity();
            count ++;
        }
        //   System.out.println("TEMp"+avgtemp+"WIND"+avgwindspeed+"Count"+count);
        avgtemperature1 = (avgtemp/count);
        avgwindspeed1 = (avgwindspeed/count);
        avghumidity1 = (avghumidity/count);
        //System.out.println("TEMp"+avgtemperature1+"WIND"+avgwindspeed1+"Count"+count);
        ShowGraphJPanel   showgraph = new ShowGraphJPanel(container,avghumidity1,avgtemperature1,avgwindspeed1,From,To);
        container.add("ShowGraphJPanel", showgraph);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnGraphActionPerformed

    private void btnPrintOnClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintOnClickActionPerformed
        // TODO add your handling code here:
        try{
            MessageFormat header = new MessageFormat("Report");
            MessageFormat footer = new MessageFormat("");
            
            tblAssign.print(JTable.PrintMode.FIT_WIDTH, header,footer);
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnPrintOnClickActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGraph;
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblAssign;
    // End of variables declaration//GEN-END:variables
}
