/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EnvironmentGettingAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Inventory.Inventory;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import userinterface.ProviderInventoryAdminWorkArea.*;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class EnvironmentViewInventoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageInventoryJPanel
     */
    private JPanel container;
    private UserAccount account;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem business;

    public EnvironmentViewInventoryJPanel(JPanel container, Organization organization, UserAccount account, EcoSystem business, Enterprise enterprise) {
        initComponents();
        this.container = container;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        pop();
        populateTable();
        System.out.println("ORGANIZATION"+this.organization+this.enterprise);
    }

    private  void pop(){
        String flag = "false";
        WorkRequest request3 = null;
        System.out.println("ENTER");
        System.out.println("CHECK1"+organization.getWorkQueue().getWorkRequestList());
     for(WorkRequest request2:organization.getWorkQueue().getWorkRequestList()){
         System.out.println("ORDQR"+request2.getStatus());
             if(request2.getStatus().equals("Completed")){
                request3 = request2;
             /*   if(organization.getInventoryDirectory().getInventoryList().isEmpty()){
                    organization.getInventoryDirectory().createInventory(request2.getProduct(),request2.getPrice(),request2.getQuantity());
                }
                */
                for(Inventory inventory:organization.getInventoryDirectory().getInventoryList()){
                    if(inventory.getProductName().equals(request2.getProduct())){
                        flag = "true";
                        inventory.setProductQuantity(inventory.getProductQuantity()+request2.getQuantity());
                    }
                }
                if(flag.equals("false")){
                    organization.getInventoryDirectory().createInventory(request2.getProduct(),request2.getPrice(),request2.getQuantity());
                }        
     }
     }
      System.out.println("REQUEST3"+request3);
     organization.getWorkQueue().deleteWorkREquest(request3);
       
        
        
        
    }
    
 public void populateTable(){
      
      DefaultTableModel dtm = (DefaultTableModel)tblInventory.getModel();
       dtm.setRowCount(0);
          
           Object[] row1 = new Object[3];
           System.out.println("INV"+organization.getInventoryDirectory().getInventoryList());
    for(Inventory inventory: organization.getInventoryDirectory().getInventoryList()){
        row1[0]= inventory.getInventoryId();
        row1[1]=inventory.getProductName();
        row1[2]=inventory.getProductQuantity();
        dtm.addRow(row1);
    }
      
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventory = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Product Name", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblInventory);
        if (tblInventory.getColumnModel().getColumnCount() > 0) {
            tblInventory.getColumnModel().getColumn(0).setResizable(false);
            tblInventory.getColumnModel().getColumn(1).setResizable(false);
            tblInventory.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 780, 410));

        btnBack.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 620, -1, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("Environment Inventory");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/background2.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInventory;
    // End of variables declaration//GEN-END:variables
}
